name: Node.js CI

on: push
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  PORT:    ${{ secrets.PORT }}
  SECRET:  ${{ secrets.SECRET }}
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    environment: dev
    steps: 
      - uses: actions/checkout@v2 --no-optional
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: create env file
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASS=${{ secrets.DB_PASS }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
