on: push
env:
  DB_USER: ${{ secrets.dev..DB_USER }}
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    environment: dev
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - name: create env file
        run: |
          touch .env
          echo DB_USER=${{ secrets.dev.DB_USER }} >> .env
      - run: node server.js
